### ISSUE TITLE
Need to finalize instructors

### ISSUE THREAD

**Issue by hlapp** [Reproducible-Science-Curriculum/2015-05-14-reproducible-science-duke#1]
Here's the semi-final list:

Instructors:
- [X] Intro: @mine-cetinkaya-rundel 
- [x] Organization: @hlapp
- [x] Automation: @fmichonneau 
- [x] Publication: @kcranston 

Additional Helpers:
- [x] @dleehr
- [x] @whitews

**Comment by dmlond** [comment]
I am interested in acting as a helper, but I am out of the country May 9-17

**Comment by hlapp** [comment]
Updated with instructor and helper commitments as of current.
